# Generated by Django 2.2.3 on 2019-07-10 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxi',
            name='PermisConduire_proprietaire',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='PermisConfiance_proprietaire',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='cin_proprietaire',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='taxi',
            name='chauffeur',
        ),
        migrations.AddField(
            model_name='taxi',
            name='chauffeur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_app.Chauffeur'),
        ),
        migrations.DeleteModel(
            name='Conduire',
        ),
    ]
